# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MQTTClientDemo' do
	pod 'MQTTKit', :git => 'https://github.com/mobile-web-messaging/MQTTKit.git'
end

target 'MQTTClientDemoTests' do

end

